### ISSUE TITLE
Snapshot channel error

### ISSUE THREAD

**Issue by silentbay** [lordmulder/Chromium-Updater#1]
OS: Win7 X64
Soft: Chromium-Updater.2015-11-02
Option: channel=snapshots

Error: Download failed: File Not Found (404). Please check your internet connection and try again.

On channel=continuous download without error.

**Comment by lordmulder** [comment]
Okay, it appears "snapshots" channel has no "x64" builds, only "continuous".

Should be fixed in 1db3480db5d19c894936e62465551a4113ea6172, try new build please:
[**Chromium-Updater.2015-11-04.zip**](http://sourceforge.net/projects/muldersoft/files/Chromium%20Updater/Testing/Chromium-Updater.2015-11-04.zip/download)

**Comment by silentbay** [comment]
works
